dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@latest
install:
  - npm ci
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  provider: netlify
  dir: dist/
  edge: true
