dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@latest
install:
  - npm ci
script:
  - npm test
before_deploy:
  - npm run build
  - envsubst < ./dist/index.html > ./dist/index.html
  - npm install -g @sentry/cli
  - envsubst < ./netlify.toml.template > ./netlify.toml
deploy:
  provider: netlify
  dir: dist/
  prod: true
  edge: true
after_deploy: ./travis/sentry-release.sh
