dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@latest
install:
  - npm ci
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  provider: netlify
  site: NETLIFY_SITE
  auth: NETLIFY_AUTH
  dir: dist/
  edge: true
